### ISSUE TITLE
New bug

### ISSUE THREAD

**Issue by JanHampelmann** [Andy4495/SWI2C#10]
Hello Andy, back again with a new comment about the SWI2C library. 
A "readFromDevice" will not work if executed sequentially to a "writeToDevice". 
The cause is an incorrect implementation of the "writeToDevice" function. 
Between "if (sendStopBit) stopBit();" and the "retun 1;" statements the "if (checkAckBit()) {stopBit(); return 0;}" statement is missing. 
I suspect this is also the case with the "int SWI2C::writeToDevice(uint8_t* buffer, uint8_t count, bool sendStopBit)" function. 
So far, all other functions are untested as I don't use them. 
Regards,
Jan.

**Comment by Andy4495** [comment]
Yes, I'll fix that one, too and push out a new release. 

As far as the comment about `int SWI2C::writeToDevice(uint8_t* buffer, uint8_t count, bool sendStopBit)` -- I don't think anything needs to change; it already checks for ACK/NACK in the `for` loop after each byte is written: 

```cpp
  for (uint8_t i = 0; i < count; i++) {
    writeByte(buffer[i]); // LSB
    if (checkAckBit()) {stopBit(); return 0;} // Immediately end transmission and return 0 if NACK detected
  }
```

What device are you using to test this? I have been using the PCF8574A, and it seems a little more tolerant of protocol issues. 

Thanks,
Andy
