### ISSUE TITLE
SWI2C - Software I2C Library

### ISSUE THREAD

**Issue by JanHampelmann** [Andy4495/SWI2C#9]
Thanks for the library, I'm happy with it. 
However, still a report of a small problem. In my humble opinion you forgot a statement in the "SWI2C::readFromDevice(uint8_t &data, bool sendStopBit)" function. 
After the "data = read1Byte()" statement, the "checkAckBit()" statement is missing. 
This causes the I2C bus readout to hang. 

Regards, Jan.

**Comment by Andy4495** [comment]
Yes, you are correct. Thanks for pointing that out!

I'll update the library and release a new version later today.

**Comment by Andy4495** [comment]
Updated and will be included in [Release 2.0.1](https://github.com/Andy4495/SWI2C/releases/tag/v2.0.1)
